name: patel_samaj_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  auto_route: ^9.2.2
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_localization: ^0.2.3
  flutter_screenutil: ^5.9.3
  get_it: ^8.0.2
  loading_animation_widget: ^1.3.0
  provider: ^6.1.2

dev_dependencies:
  flutter_lints: ^4.0.0
  auto_route_generator: ^9.0.0
  change_app_package_name: ^1.4.0
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
